name: CI/CD
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build the Anfiheft
        run: |
          .github/scripts/setup.sh
          nix-build --argstr date "$(date --date=@$(git log -1 --pretty=%ct) +%F)" --arg doCheck true
      - name: Upload the Anfiheft
        if: ${{ github.repository_owner == 'fsi-tue' && github.ref == 'refs/heads/master' }}
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          TRAVIS_COMMIT: ${{ github.sha }}
        run: |
          export NIXPKGS_COMMIT=$(curl -L "https://channels.nixos.org/nixos-unstable/git-revision")
          .github/scripts/deploy.sh
